package pft.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;
import pft.model.GroupData;

public class GroupCreationTest extends TestBase {

  @Test
  public void testGroupCreation5() {
    app.goToGroupPage();
    app.initGroupCreation();
    app.fillGroupForm(new GroupData("groop9", "gh9", "gf9"));
    app.submitGroupCreation();
    app.returnToGroupPage();
  }

}
