package pft.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pft.model.GroupData;

import java.util.List;

public class GroupDeletionTest extends TestBase {
  @BeforeMethod
  public void ensurePreconditions() {
    app.goTo().groupPage();
    if (app.group().getList().size() == 0) {
      app.group().create(new GroupData(null,"group5", "h5", "f5"));
    }
  }

  @Test
  public void testGroupDeletion() {
    List<GroupData> before = app.group().getList();
    int index = before.size() - 1;
    app.group().delete(index);
    List<GroupData> after = app.group().getList();
    Assert.assertEquals(after.size(), before.size() - 1);
    before.remove(index);
    Assert.assertEquals(after, before);
  }

}
