package pft.tests;// Generated by Selenium IDE

import org.testng.Assert;
import org.testng.annotations.Test;
import pft.model.GroupData;
import java.util.Set;

public class GroupCreationTest extends TestBase {

  @Test
  public void testGroupCreation5() {
    app.goTo().groupPage();
    Set<GroupData> before = app.group().getAll();
    app.group().create(new GroupData(null,"group5", "h5", "f5"));
    Set<GroupData> after = app.group().getAll();
    Assert.assertEquals(after.size(), before.size() + 1);
    int newElementId = after.stream().mapToInt((g) -> g.id()).max().getAsInt();
    before.add(new GroupData(newElementId, "group5", "h5", "f5"));
    Assert.assertEquals(before, after);
  }
}
