package pft;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class ContactCreationTest extends TestBase{

  @Test
  public void testContactCreation() {
    goToContactAddPage();
    fillContactForm(new ContactData("Juliett", "Suslenkova", "Corporation", "Academ", "89567845736","jsus648@gtkd,ru"));
    submitContactCreation();
    returnToHomePage();
  }

}
