package pft;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class ContactCreationTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @BeforeMethod
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1198, 804));
    login("admin", "secret");
  }

  private void login(String username, String password) {
    driver.findElement(By.name("user")).sendKeys(username);
    driver.findElement(By.name("pass")).sendKeys(password);
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  @AfterMethod
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void testContactCreation() {
    goToContactAddPage();
    fillContactForm(new ContactData("Juliett", "Suslenkova", "Corporation", "Academ", "89567845736","jsus648@gtkd,ru"));
    submitContactCreation();
    returnToHomePage();
  }

  private void submitContactCreation() {
    driver.findElement(By.name("submit")).click();
  }

  private void fillContactForm(ContactData contactData) {
    driver.findElement(By.name("firstname")).sendKeys(contactData.first_name());
    driver.findElement(By.name("lastname")).sendKeys(contactData.last_name());
    driver.findElement(By.name("company")).sendKeys(contactData.company());
    driver.findElement(By.name("address")).sendKeys(contactData.address());
    driver.findElement(By.name("mobile")).sendKeys(contactData.mobile_phone());
    driver.findElement(By.name("email")).sendKeys(contactData.email());
  }

  private void goToContactAddPage() {
    driver.findElement(By.linkText("add new")).click();
  }

  private void returnToHomePage() {
    driver.findElement(By.linkText("home page")).click();
  }
}
