package pft;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class GroupCreationTest extends TestBase {

  @Test
  public void testGroupCreation5() {
    goToGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("groop9", "gh9", "gf9"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
