package pft;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class GroupDeletionTest extends TestBase {


  @Test
  public void testGroupCreation5() {
    goToGroupPage();
    selectGroup();
    deleteGroup();
    returnToGroupPage();
  }

}
